### ISSUE TITLE
Implement JWT Token Generation for User Registration API

### ISSUE THREAD

**Issue by souptik4572** [souptik4572/JustAskIt#4]
### **Description:**

**Objective:**
Extend the existing user registration API to generate and return a JWT token upon successful registration. Currently, the JWT token is generated and returned only for the Login API. This enhancement aims to ensure consistency in token-based authentication by providing a JWT token during both registration and login.

**Current Implementation:**
JWT token generation is implemented for the Login API. Below is an example of the request and response for the Login API:

**Login API Request:**
```
curl --location 'http://127.0.0.1:8000//api/user/login/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "janedoe@yahoo.in",
    "password": "password"
}'
```

**Login API Response:**
```
{
    "success": true,
    "message": "Successfully logged in",
    "data": {
        "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNzI3ODA1ODY1fQ.b9XCK7qzLick_GoRDetjZSGjjNg8IF95vD4LTcmd6ZPxOqLF4Uc0IGQ6Jl_IOcxGujySOokU0gt6flQ-ht_VHQ"
    }
}
```

**Scope of Work:**

1. **JWT Token Generation for Registration API**: Implement JWT token generation for the `register user` API, similar to the existing Login API.
2. **Response Format**: Ensure that the response for the registration API follows the same format as the Login API.

**Acceptance Criteria:**

- [ ] The `register user` API generates and returns a JWT token upon successful registration.
- [ ] The response structure is consistent with the response for the Login API.

**Additional Notes:**
This implementation will improve user experience by allowing newly registered users to receive a token immediately, reducing the need to log in separately after registration.

**Comment by Essogbe** [comment]
Hi @souptik4572 could you please assign me this issue and add the Hacktoberfest label? I would love to work on it. Thanks!

**Comment by souptik4572** [comment]
Sure @Essogbe. Please go ahead, I will assign you to this issue.
